/* 削除 */
DROP TABLE PORTABLERIS_TERMINALINFO CASCADE CONSTRAINTS PURGE;

/* 作成 */
CREATE TABLE PORTABLERIS_TERMINALINFO(
	HOST				VARCHAR2(64)	NOT NULL,
	IPADDRESS			VARCHAR2(64)	NOT NULL,
	KENSASITU_ID			VARCHAR2(10),
	KENSAKIKI_ID			VARCHAR2(10),
	KANJA_NYUGAI			VARCHAR2(2),
	KENSATYPE_ID			VARCHAR2(16)
);

/* コメント */
COMMENT ON TABLE PORTABLERIS_TERMINALINFO IS 'ポータブルRIS用端末設定テーブル';
COMMENT ON COLUMN PORTABLERIS_TERMINALINFO.HOST IS '端末識別名';
COMMENT ON COLUMN PORTABLERIS_TERMINALINFO.IPADDRESS IS 'IPアドレス';
COMMENT ON COLUMN PORTABLERIS_TERMINALINFO.KENSASITU_ID IS '実施検査室ID';
COMMENT ON COLUMN PORTABLERIS_TERMINALINFO.KENSAKIKI_ID IS '実施検査機器ID';
COMMENT ON COLUMN PORTABLERIS_TERMINALINFO.KANJA_NYUGAI IS '入外区分';
COMMENT ON COLUMN PORTABLERIS_TERMINALINFO.KENSATYPE_ID IS '検査種別ID';

EXIT;
