select
	r.RIS_ID,
	r.KANJA_ID,
	r.STATUS,
	r.SEX,
	r.KANJISIMEI,
	r.KANASIMEI,
	r.BYOUTOU,
	r.BYOUSITU,
	TRUNC((TO_NUMBER(TO_CHAR(SYSDATE,'yyyymmdd')) - r.BIRTHDAY)/10000,0) as AGE,
	r.IRAI_SECTION,
	r.IRAI_DOCTOR_NAME || ' ' || r.IRAIDOCTOR_TEL as IRAI_DOCTOR_NAME,
	r.RENRAKU_MEMO,
	r.ACNO,
	r.RECEIPTNUMBER,
	r.RECEIPTDATE,
	case
		when r.STATUS >= 10 then r.EX_KENSA_DATE
		when r.STATUS < 10 then r.ORDER_KENSA_DATE
	end as KENSA_DATE,
	r.ORDERCOMMENT_ID,
	r.KENSA_SIJI,
	o.RINSYOU,
	r.REMARKS,
	p.HANDICAPPED,
	p.INFECTION,
	p.CONTRAINDICATION,
	p.ALLERGY,
	p.PREGNANCY,
	p.NOTES,
	p.EXAMDATA
from
	RISSUMMARYVIEW r,
	PATIENTINFO p,
	EXMAINTABLE e,
	ORDERINDICATETABLE o
where
	r.RIS_ID = e.RIS_ID
and
	r.RIS_ID = o.RIS_ID
and
	r.KANJA_ID = p.KANJA_ID
and
	r.RIS_ID = :RIS_ID
and
	r.KENSA_DATE = :KENSA_DATE


select
	b.BUI_NAME,
	h.HOUKOU_NAME,
	s.SAYUU_NAME,
	k.KENSAHOUHOU_NAME,
	e.BUICOMMENT
from
	BUIMASTER b,
	HOUKOUMASTER h,
	SAYUUMASTER s,
	KENSAHOUHOUMASTER k,
	EXBUITABLE e
where
	e.RIS_ID = :RIS_ID
and
	e.BUI_ID = b.BUI_ID(+)
and
	e.HOUKOU_ID = h.HOUKOU_ID(+)
and
	e.SAYUU_ID = s.SAYUU_ID(+)
and
	e.KENSAHOUHOU_ID = k.KENSAHOUHOU_ID(+)
